[package]
name = "nvim-spotify"
version = "0.1.0"
authors = ["Srishan Bhattarai <srishanbhattarai@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.11.2", features = ["blocking"] }
neovim-lib = "0.6.1"
soup = "0.5.1"
